# -*- coding: utf-8 -*-
"""neuro_wheels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdC8uc28kz6-bvF2JUWaNg2OL6qqi2ob
"""


import streamlit as st
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# Load the model and tokenizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
ckpt = "google/gemma-3-1b-pt"  # This is an example model, use the right model path
tokenizer = AutoTokenizer.from_pretrained(ckpt)
model = AutoModelForCausalLM.from_pretrained(ckpt, torch_dtype=torch.bfloat16, device_map="auto").to(device)

# Function to generate a more structured response
def get_response(user_input):
    # Specific prompt with step-by-step reasoning
    prompt = """
    You are an AI assistant designed to answer simple questions.
    Please restrict your answer to the exact question asked.
    Think step by step, use careful reasoning.
    Question: {question}
    Answer:
    """

    # Format the prompt with the user's input
    formatted_prompt = prompt.format(question=user_input)

    # Tokenize the formatted prompt
    model_inputs = tokenizer(formatted_prompt, return_tensors="pt").to(device)
    input_len = model_inputs["input_ids"].shape[-1]

    # Generate the response using the model
    with torch.no_grad():
        generation = model.generate(**model_inputs, temperature=0.5, max_length=256, do_sample=True)
        generation = generation[0][input_len:]

    # Decode and return the response
    response = tokenizer.decode(generation, skip_special_tokens=True)
    return response

# Main function to display the chat interface
def show_chat_page():
    st.title("🧠 NeuroGuide - Your Brainy Assistant")

    # User input section
    user_input = st.text_input("Ask NeuroGuide anything...")

    if user_input:
        # Get the model's response based on the structured prompt
        bot_response = get_response(user_input)
        st.write(f"User: {user_input}")
        st.write(f"NeuroGuide: {bot_response}")

if __name__ == "__main__":
    show_chat_page()
